version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: install dependencies
          command: npm install
  lint:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: change directory
          command: |
            cd webapp
            command: npm install
            npm run lint
workflows:
  test-workflow:
    jobs:
      - build
      - lint
