version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: install dependencies
          command: npm install
  lint:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: change directory
          command: |
            cd webapp
            npm install
            npm run lint
  
  deploy_tmp:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - add_ssh_keys
      - run:
          name: deploy to prod
          command: |
            echo -e "Host git-codecommit.*.amazonaws.com\n   User ${AWS_SSH_KEY_ID}\n   StrictHostKeyChecking no" > ${HOME}/.ssh/config
            git push ssh://git-codecommit.ap-northeast-1.amazonaws.com/v1/repos/sample-webapp
workflows:
  test-workflow:
    jobs:
      - build
      - lint: 
          filters:
            branches:
              only:
                - codeDeplo_test
            tags:
              ignore: /^force-push*/

      - deploy_tmp:
          requires:
            - build
            - lint
          filters:
            branches:
              only:
                - main
